# Generated by Django 3.2.13 on 2025-09-29 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20250923_2250'),
    ]

    operations = [
        migrations.AddField(
            model_name='demo',
            name='password',
            field=models.CharField(default='testpassword', max_length=100),
        ),
        migrations.AddField(
            model_name='demo',
            name='username',
            field=models.CharField(default='testuser', max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='demo',
            unique_together={('username', 'password')},
        ),
        migrations.RemoveField(
            model_name='demo',
            name='name',
        ),
    ]
