# Generated by Django 3.2.13 on 2025-10-01 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20250929_1412'),
    ]

    operations = [
        migrations.CreateModel(
            name='LastDemo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastLoggedIn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='last_demo_used', to='api.demo')),
            ],
        ),
    ]
