# Generated by Django 3.2.13 on 2025-10-04 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_lastdemo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LastDemo',
        ),
    ]
