# Generated by Django 3.2.13 on 2025-11-25 20:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_delete_lastdemo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='newcrew', max_length=100)),
                ('symbol', models.CharField(default='skull', max_length=100)),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crew', to='api.demo')),
            ],
        ),
        migrations.CreateModel(
            name='Crewmate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='crewmember', max_length=100)),
                ('color', models.CharField(default='blue', max_length=30)),
                ('epithet', models.CharField(default='swabber', max_length=100)),
                ('enlistment', models.DateField()),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crewmates', to='api.crew')),
            ],
        ),
    ]
