# Generated by Django 3.2.13 on 2025-12-03 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_crew_crewmate'),
    ]

    operations = [
        migrations.AddField(
            model_name='crewmate',
            name='retired',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterUniqueTogether(
            name='crew',
            unique_together={('name', 'symbol', 'organizer')},
        ),
        migrations.AlterUniqueTogether(
            name='crewmate',
            unique_together={('name', 'enlistment', 'epithet', 'team', 'color')},
        ),
    ]
